spring:
  application:
    name: Worldwide windsurfer's weather app

# External API data
weatherbit:
  io:
   api:
     url: https://api.weatherbit.io/v2.0/forecast/daily
     key: 49aeca2ceb054835be54e73f55d1b7af
   max:
     limit:
       dates: 7

# Embedded list of locations
weather:
  locations:
    Jastarnia, Bridgetown, Fortaleza, Pissouri, La Morne

